# Generated by Django 5.2.4 on 2025-08-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='username',
            new_name='user_name',
        ),
    ]
