# Generated by Django 5.2.4 on 2025-08-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_owner_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_name',
            new_name='username',
        ),
    ]
